wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.51.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1746679065.137843
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.13.7
      6: 4.51.3
      8:
      - 5
activation_fn:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 128
convert_to_one_hot:
  desc: null
  value: false
d_head:
  desc: null
  value: 64
d_mlp:
  desc: null
  value: 256
d_model:
  desc: null
  value: 256
device:
  desc: null
  value: cpu
eval_episodes:
  desc: null
  value: 10
eval_frequency:
  desc: null
  value: 100
eval_max_time_steps:
  desc: null
  value: 200
eval_num_envs:
  desc: null
  value: 8
exp_name:
  desc: null
  value: MiniGrid-Dynamic-Obstacles-8x8-v0-Refactor
gated_mlp:
  desc: null
  value: null
initial_rtg:
  desc: null
  value:
  - 1
layer_norm:
  desc: null
  value: null
lr:
  desc: null
  value: 5.0e-05
lr_end:
  desc: null
  value: 1.0e-07
mlp_train_epochs:
  desc: null
  value: 15
mode:
  desc: null
  value: rtg
model_type:
  desc: null
  value: decision_transformer
n_ctx:
  desc: null
  value: 302
n_heads:
  desc: null
  value: 4
n_layers:
  desc: null
  value: 2
num_cycles:
  desc: null
  value: 3
optimizer:
  desc: null
  value: AdamW
pct_traj:
  desc: null
  value: 1
prob_go_from_end:
  desc: null
  value: 0.5
scheduler:
  desc: null
  value: CosineAnnealingWarmup
seed:
  desc: null
  value: 1
state_embedding_type:
  desc: null
  value: grid
task_loss_weight:
  desc: null
  value: 0.1
test_epochs:
  desc: null
  value: 3
test_frequency:
  desc: null
  value: 100
time_embedding_type:
  desc: null
  value: embedding
track:
  desc: null
  value: true
train_epochs:
  desc: null
  value: 1
trajectory_path:
  desc: null
  value:
  - ../trajectories/DoorKey2.gz
  - ../trajectories/LavaCrossing2.gz
  - ../trajectories/SimpleCrossing2.gz
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: DecisionTransformerInterpretability
warm_up_steps:
  desc: null
  value: 1000
weight_decay:
  desc: null
  value: 0.001
