wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.18
    start_time: 1754451162.462235
    t:
      1:
      - 12
      - 55
      2:
      - 12
      - 55
      3:
      - 13
      - 23
      4: 3.10.18
      5: 0.13.7
      8:
      - 5
